from . import person
from . import doctor
from . import patient
from . import type_disease
from . import patient_visit
from . import diagnosis
from . import category_disease
from . import history_personal_doctor
from . import doctor_schedule
from . import analysis
